-- ============================================================
-- GymGram — Referencia de schema (Supabase, proyecto gymgram-beta)
-- sa-east-1 / São Paulo · ref: qnrpyaoyzecjbryejccm
-- ============================================================
--
-- ⚠️  FUENTE DE VERDAD: este archivo NO es el schema completo.
--     El DDL autoritativo vive en supabase/migrations/ (64+ archivos, en orden
--     cronológico). Este archivo es solo un INVENTARIO de referencia rápido,
--     regenerado el 2026-05-24. Para el detalle de columnas/políticas/funciones
--     de cualquier tabla, busca su migración correspondiente.
--
-- RLS: las 50 tablas de `public` tienen Row Level Security HABILITADO.
--      Verificado con get_advisors (0 hallazgos rls_disabled). Las políticas
--      usan auth.uid() (owner-scoped) y los escritos sensibles van por RPCs
--      SECURITY DEFINER con guard interno o por service_role (edge functions).
--
-- ============================================================
-- INVENTARIO DE TABLAS (public) — 50 tablas, todas con RLS
-- ============================================================
--
-- Social / feed
--   profiles                  Perfil de usuario (incl. referral_code, referred_by,
--                             subscription_tier/variant). Vista: public_profiles.
--   posts, likes, comments, saved_posts, post_views
--   follows, notifications
--
-- Mensajería
--   chats, chat_participants, messages, blocked_users, reports, device_tokens
--
-- Entrenamiento
--   routines, routine_exercises, routine_copies, routine_impact_stats
--   exercise_catalog (175 ejercicios), workout_logs, set_logs
--   user_strength_records
--
-- Nutrición
--   meal_plans, meal_items, food_logs, water_logs, weight_logs
--   custom_foods (189), ai_meal_templates (200 recetas con ingredientes)
--   nutrition_goals, user_dietary_restrictions
--   user_recipes, user_recipe_ingredients, saved_recipes
--
-- Onboarding / perfil
--   user_onboarding_data, profile_change_logs
--
-- Gamificación
--   user_badges, medal_submissions
--
-- Modo Ranked (competitivo)
--   ranked_seasons, user_ranked_profile, rp_transactions
--   weekly_missions, user_mission_progress, season_rewards
--   (vista materializada: ranked_leaderboard_view)
--
-- IA (RAG sobre exercise_catalog + custom_foods/ai_meal_templates)
--   ai_weekly_checkins, workout_feedback, ai_monthly_summaries
--   ai_trainer_config, ai_trainer_messages
--   ai_usage_events  (tope duro de costo IA por usuario/mes)
--
-- ============================================================
-- Migraciones de hardening recientes (2026-05-24):
--   20260524000002_security_hardening_advisors  (security_invoker, search_path,
--                                                 política huérfana, matview→anon)
--   20260524000003_storage_no_listing           (buckets públicos sin listing)
--   20260524000004_revoke_anon_execute          (EXECUTE de RPCs/triggers)
--   20260524000005_fk_covering_indexes          (22 índices FK para escala)
--   20260524000006_ai_usage_cap                 (tabla ai_usage_events)
--   20260524000007_referrals                    (referral_code, redeem_referral)
-- ============================================================
