-- Base de datos de alimentos chilenos curados para GymGram Beta (CL).
-- La IA selecciona recetas de esta tabla según objetivo, momento y preferencias.
-- Macros son POR PORCIÓN SERVIDA (campo porcion_g), no por 100g.
-- Fuente: estimaciones propias calibradas con USDA FoodData Central.

create table if not exists public.ai_meal_templates (
  id                   uuid          primary key default gen_random_uuid(),
  external_id          text          not null unique,
  nombre               text          not null,
  categoria_dificultad text          not null
                                     check (categoria_dificultad in ('Muy fácil', 'Normal', 'Gourmet')),
  modo_dieta           text          not null,
  momento_dia          text[]        not null default '{}',
  porcion_g            integer,
  kcal                 integer       not null,
  proteina_g           numeric(6,1)  not null,
  carbohidratos_g      numeric(6,1)  not null,
  grasas_g             numeric(6,1)  not null,
  fibra_g              numeric(6,1),
  sodio_mg             numeric(7,1),
  ingredientes_base    text,
  tags                 text[]        not null default '{}',
  -- Valores válidos: 'perder_grasa', 'mantener', 'ganar_musculo'
  objetivo_recomendado text[]        not null default '{}',
  costo_estimado_clp   integer,
  nota_para_ia         text,
  source_url           text,
  confiabilidad        text          not null default 'estimado'
                                     check (confiabilidad in ('estimado','calculado','validado_nutricionista')),
  pais_origen          text          not null default 'CL',
  activo               boolean       not null default true,
  created_at           timestamptz   not null default now()
);

-- Índices GIN para filtros de arrays (objetivo, momento, tags)
create index if not exists ai_meal_templates_objetivo_idx
  on public.ai_meal_templates using gin (objetivo_recomendado);

create index if not exists ai_meal_templates_momento_idx
  on public.ai_meal_templates using gin (momento_dia);

create index if not exists ai_meal_templates_tags_idx
  on public.ai_meal_templates using gin (tags);

create index if not exists ai_meal_templates_dificultad_idx
  on public.ai_meal_templates (categoria_dificultad);

alter table public.ai_meal_templates enable row level security;

-- Catálogo público: cualquier usuario autenticado puede leer recetas activas
drop policy if exists "ai_meal_templates: select authenticated" on public.ai_meal_templates;
create policy "ai_meal_templates: select authenticated"
  on public.ai_meal_templates
  for select
  to authenticated
  using (activo = true);

-- ─── DATOS: 45 recetas chilenas curadas ─────────────────────────────────────
insert into public.ai_meal_templates
  (external_id, nombre, categoria_dificultad, modo_dieta, momento_dia,
   porcion_g, kcal, proteina_g, carbohidratos_g, grasas_g, fibra_g, sodio_mg,
   ingredientes_base, tags, objetivo_recomendado,
   costo_estimado_clp, nota_para_ia, source_url, confiabilidad)
values
  ('CL-001', 'Arroz con atún', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   350, 520, 34, 78, 9, 4, 680,
   'arroz blanco cocido, atún al agua, tomate/cebolla opcional', ARRAY['alto_proteina','economico','rapido'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1500, 'Ideal cuando el usuario necesita proteína barata y rápida. Cuidar sodio del atún.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-002', 'Arroz con pollo', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   380, 610, 43, 82, 12, 4, 520,
   'arroz cocido, pechuga de pollo, aceite, ensalada opcional', ARRAY['alto_proteina','meal_prep'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1800, 'Buena receta base para planes simples; ajustar arroz según objetivo.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-003', 'Arroz con carne molida', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   390, 690, 36, 80, 24, 4, 610,
   'arroz cocido, carne molida, sofrito', ARRAY['alto_caloria','facil'], ARRAY['ganar_musculo','mantener'],
   2200, 'Útil para volumen; para perder grasa usar carne magra y menos aceite.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-004', 'Arroz con huevo', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   330, 570, 22, 76, 19, 3, 420,
   'arroz cocido, 2 huevos, aceite mínimo', ARRAY['economico','rapido','vegetariano'], ARRAY['mantenimiento','ganar_musculo'],
   1000, 'Barato y salvador; queda corto de proteína para volumen serio.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-005', 'Puré con pollo', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   400, 590, 42, 58, 19, 5, 620,
   'puré de papas, pechuga o tuto de pollo, leche/mantequilla opcional', ARRAY['chileno','alto_proteina'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1900, 'Para definición usar puré con poca mantequilla y pollo a la plancha.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-006', 'Puré con carne', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   420, 720, 38, 57, 35, 5, 700,
   'puré de papas, posta/carne molida, sofrito', ARRAY['casero','alto_caloria'], ARRAY['ganar_musculo','mantener'],
   2500, 'Bueno para usuarios con alto gasto calórico; controlar grasas.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-007', 'Pan con jamonada', 'Muy fácil', 'Casero / Normal', ARRAY['desayuno','once','colacion'],
   120, 330, 14, 45, 10, 3, 850,
   'marraqueta o hallulla, jamonada', ARRAY['economico','once','rapido'], ARRAY['mantenimiento'],
   900, 'No abusar por sodio/ultraprocesado; usar ocasionalmente.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-008', 'Pan con queso', 'Muy fácil', 'Casero / Normal', ARRAY['desayuno','once','colacion'],
   130, 390, 17, 44, 16, 3, 720,
   'pan, queso gauda/chanco', ARRAY['once','rapido'], ARRAY['mantenimiento','ganar_musculo'],
   1100, 'Mejor si se acompaña con fruta o tomate; grasas moderadas.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-009', 'Pan con mantequilla', 'Muy fácil', 'Casero / Normal', ARRAY['desayuno','once'],
   100, 330, 8, 45, 13, 2, 520,
   'pan, mantequilla', ARRAY['economico','rapido'], ARRAY['mantenimiento'],
   700, 'Solo energía rápida; poca proteína. No es ideal como comida principal.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-010', 'Avena con leche y plátano', 'Muy fácil', 'Casero / Normal', ARRAY['desayuno','colacion'],
   320, 430, 18, 72, 9, 8, 180,
   'avena, leche, plátano, canela opcional', ARRAY['alto_fibra','barato','pre_entreno'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1000, 'Excelente desayuno base. Ajustar porción de avena según calorías.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-011', 'Yogur natural con avena y fruta', 'Muy fácil', 'Casero / Normal', ARRAY['desayuno','colacion'],
   280, 360, 20, 55, 7, 6, 140,
   'yogur natural/proteico, avena, fruta', ARRAY['alto_proteina','fibra'], ARRAY['perder_grasa','mantener'],
   1500, 'Buena opción liviana; usar yogur sin azúcar para definición.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-012', 'Tortilla de huevo con pan', 'Muy fácil', 'Casero / Normal', ARRAY['desayuno','once','cena'],
   260, 460, 26, 38, 23, 3, 530,
   '2-3 huevos, pan, tomate/espinaca opcional', ARRAY['rapido','alto_proteina'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1300, 'Buena cena simple; bajar pan si el objetivo es déficit.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-013', 'Fideos a la boloñesa', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   420, 760, 38, 95, 25, 7, 780,
   'fideos, carne molida, salsa de tomate, sofrito', ARRAY['clasico','alto_caloria'], ARRAY['ganar_musculo','mantener'],
   2300, 'Muy útil para volumen; para definición usar porción menor de pasta y carne magra.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-014', 'Cazuela de vacuno', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   600, 620, 42, 60, 22, 8, 850,
   'vacuno, papa, zapallo, choclo, arroz, verduras', ARRAY['chileno','plato_fuerte'], ARRAY['mantenimiento','ganar_musculo'],
   2800, 'Plato completo; ajustar papa/arroz para controlar carbohidratos.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-015', 'Cazuela de pollo', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   600, 540, 39, 58, 17, 8, 780,
   'pollo, papa, zapallo, choclo, arroz, verduras', ARRAY['chileno','plato_fuerte'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   2300, 'Más liviana que vacuno; buena para dieta normal chilena.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-016', 'Porotos con riendas', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   450, 620, 24, 95, 16, 18, 900,
   'porotos, tallarines, zapallo, longaniza opcional', ARRAY['chileno','legumbres','alto_fibra'], ARRAY['mantenimiento','ganar_musculo'],
   1700, 'Alta fibra y saciedad; para definición reducir longaniza/aceite.', 'https://www.recetasnestle.cl/recetas/receta-porotos-con-rienda', 'estimado'),
  ('CL-017', 'Garbanzos guisados con arroz', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   430, 580, 22, 88, 15, 16, 760,
   'garbanzos, arroz, verduras, sofrito', ARRAY['legumbres','economico','alto_fibra'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1600, 'Muy buena para dieta económica; complementar con huevo/pollo si falta proteína.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-018', 'Lentejas con arroz', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   430, 560, 24, 86, 12, 18, 700,
   'lentejas, arroz, zanahoria, cebolla, ajo', ARRAY['legumbres','economico','alto_fibra'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1400, 'Top para Chile: barata, llenadora y nutritiva. Poco glamour, mucho ROI.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-019', 'Carbonada', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   550, 520, 32, 58, 17, 8, 820,
   'carne, papas, zapallo, choclo, verduras, arroz opcional', ARRAY['chileno','sopa','completo'], ARRAY['perder_grasa','mantener'],
   2200, 'Buena comida casera con volumen alto y calorías moderadas.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-020', 'Pantrucas', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   500, 560, 30, 72, 17, 5, 900,
   'masa de harina, carne/huevo, caldo, verduras', ARRAY['chileno','invierno'], ARRAY['mantenimiento','ganar_musculo'],
   1800, 'Buena en días fríos; controlar harina si hay déficit calórico.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-021', 'Charquicán con huevo', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   480, 610, 28, 70, 24, 10, 760,
   'papa, zapallo, verduras, carne molida, huevo', ARRAY['chileno','verduras'], ARRAY['mantenimiento','ganar_musculo'],
   2100, 'Gran opción para meter verduras sin sentirse en castigo fitness.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-022', 'Tomaticán con arroz', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   430, 570, 29, 76, 17, 7, 680,
   'tomate, choclo, carne, arroz', ARRAY['chileno','verano'], ARRAY['perder_grasa','mantener'],
   2100, 'Buena receta chilena liviana si se usa carne magra.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-023', 'Pastel de choclo', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   450, 720, 34, 82, 29, 8, 850,
   'choclo molido, pino, pollo/huevo, aceituna', ARRAY['chileno','alto_caloria'], ARRAY['mantenimiento','ganar_musculo'],
   3000, 'Más calórico; usar con moderación en definición.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-024', 'Humitas con ensalada chilena', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   420, 520, 15, 86, 14, 9, 620,
   'humitas, tomate, cebolla', ARRAY['chileno','vegetariano'], ARRAY['mantenimiento'],
   2200, 'Buena opción vegetariana, pero proteína baja.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-025', 'Pollo arvejado con arroz', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   430, 620, 43, 72, 17, 7, 760,
   'pollo, arvejas, zanahoria, arroz', ARRAY['alto_proteina','casero'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   2200, 'Muy buen plato para planes fitness normales.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-026', 'Tallarines con atún y tomate', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   390, 650, 35, 90, 13, 6, 780,
   'pasta, atún, salsa tomate', ARRAY['rapido','alto_proteina'], ARRAY['mantenimiento','ganar_musculo'],
   1700, 'Versión mejorada de tallarines rápidos; buen balance precio/proteína.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-027', 'Ensalada de pollo con papas cocidas', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   420, 490, 42, 45, 15, 7, 520,
   'pollo, papas, lechuga, tomate, aceite oliva opcional', ARRAY['liviano','alto_proteina'], ARRAY['perder_grasa','mantener'],
   2300, 'Buena para déficit sin quedar con hambre.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-028', 'Jurel con arroz y ensalada', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   400, 600, 38, 70, 19, 6, 920,
   'jurel en lata, arroz, tomate/lechuga', ARRAY['economico','omega3','alto_proteina'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1600, 'Muy chileno y barato; ojo sodio por lata.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-029', 'Salmón con quinoa y palta', 'Gourmet', 'Normal / Gourmet', ARRAY['almuerzo','cena'],
   420, 760, 43, 55, 40, 10, 520,
   'salmón, quinoa, palta, ensalada', ARRAY['premium','omega3','alto_proteina'], ARRAY['mantenimiento','ganar_musculo'],
   5500, 'Perfecta para plan premium; alto costo y grasas saludables.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-030', 'Pollo al curry con arroz basmati', 'Gourmet', 'Normal / Gourmet', ARRAY['almuerzo','cena'],
   430, 710, 44, 82, 22, 5, 760,
   'pollo, curry, leche de coco light, arroz basmati', ARRAY['gourmet','alto_proteina'], ARRAY['ganar_musculo','mantener'],
   3600, 'Más sabrosa que pollo-arroz clásico; controlar leche de coco.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-031', 'Bowl de camarones, arroz y mango', 'Gourmet', 'Gourmet', ARRAY['almuerzo','cena'],
   380, 610, 38, 78, 15, 6, 700,
   'camarones, arroz, mango, palta opcional, verduras', ARRAY['premium','mariscos'], ARRAY['perder_grasa','mantener'],
   5200, 'Liviano y pro; no apto si el usuario busca comida ultra económica.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-032', 'Lomo liso con papas rústicas y ensalada', 'Gourmet', 'Gourmet', ARRAY['almuerzo','cena'],
   480, 820, 52, 55, 42, 7, 780,
   'lomo liso, papas, ensalada, aceite oliva', ARRAY['premium','alto_proteina'], ARRAY['ganar_musculo','mantener'],
   6500, 'Buena comida alta en proteína; cara y calórica.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-033', 'Risotto de champiñones y pollo', 'Gourmet', 'Gourmet', ARRAY['almuerzo','cena'],
   420, 740, 39, 78, 29, 4, 860,
   'arroz arborio, champiñones, pollo, queso parmesano', ARRAY['gourmet','cremoso'], ARRAY['ganar_musculo','mantener'],
   4200, 'Rico pero denso en calorías; no todos tendrán arborio/parmesano.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-034', 'Pasta integral con pesto y pollo', 'Gourmet', 'Normal / Gourmet', ARRAY['almuerzo','cena'],
   400, 780, 45, 82, 30, 9, 720,
   'pasta integral, pollo, pesto, parmesano', ARRAY['alto_proteina','alto_caloria'], ARRAY['ganar_musculo','mantener'],
   3800, 'Ideal volumen limpio; pesto suma muchas calorías rápido.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-035', 'Ensalada César con pollo versión fitness', 'Gourmet', 'Normal / Gourmet', ARRAY['almuerzo','cena'],
   350, 520, 42, 24, 25, 5, 850,
   'pollo, lechuga, crutones, parmesano, salsa yogurt', ARRAY['bajo_carbo','alto_proteina'], ARRAY['perder_grasa','mantener'],
   3500, 'Buena para déficit si salsa es ligera; ojo con aderezos comerciales.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-036', 'Tacos de carne magra con palta', 'Gourmet', 'Normal / Gourmet', ARRAY['almuerzo','cena'],
   360, 680, 38, 58, 30, 9, 780,
   'tortillas, carne magra, palta, verduras', ARRAY['gourmet','alto_proteina'], ARRAY['mantenimiento','ganar_musculo'],
   4000, 'Más entretenido para adherencia; controlar cantidad de tortillas.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-037', 'Poke bowl de atún/salmón', 'Gourmet', 'Gourmet', ARRAY['almuerzo','cena'],
   420, 700, 42, 78, 24, 7, 900,
   'pescado, arroz sushi, palta, edamame, soya', ARRAY['premium','alto_proteina'], ARRAY['mantenimiento','ganar_musculo'],
   6500, 'Muy premium; cuidado sodio por soya.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-038', 'Omelette de claras con salmón ahumado', 'Gourmet', 'Gourmet', ARRAY['desayuno','cena'],
   280, 420, 45, 12, 18, 3, 980,
   'claras, huevo, salmón ahumado, espinaca', ARRAY['bajo_carbo','premium'], ARRAY['perder_grasa','mantener'],
   4800, 'Alto en proteína; sodio alto por salmón ahumado.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-039', 'Wrap integral de pollo, palta y queso crema light', 'Gourmet', 'Normal / Gourmet', ARRAY['almuerzo','colacion'],
   320, 560, 39, 48, 22, 7, 760,
   'tortilla integral, pollo, palta, queso crema light', ARRAY['portable','alto_proteina'], ARRAY['perder_grasa','mantener'],
   3200, 'Buena opción para universidad/trabajo; fácil de llevar.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-040', 'Ñoquis con salsa de tomate y pavo', 'Gourmet', 'Normal / Gourmet', ARRAY['almuerzo','cena'],
   420, 690, 36, 100, 14, 7, 820,
   'ñoquis, pavo molido, salsa tomate', ARRAY['gourmet','alto_carbo'], ARRAY['ganar_musculo','mantener'],
   3800, 'Buen carb-load; menos grasa que boloñesa tradicional.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-041', 'Batido de leche, plátano y mantequilla de maní', 'Muy fácil', 'Normal / Gourmet', ARRAY['desayuno','colacion','post_entreno'],
   400, 620, 25, 72, 26, 7, 220,
   'leche, plátano, avena opcional, mantequilla maní', ARRAY['alto_caloria','post_entreno'], ARRAY['ganar_musculo'],
   2200, 'Para subir calorías fácil; no recomendado diario en déficit.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-042', 'Sándwich integral de pollo', 'Muy fácil', 'Casero / Normal', ARRAY['desayuno','once','colacion'],
   260, 480, 38, 48, 14, 6, 720,
   'pan integral, pollo, tomate, lechuga, yogurt/mayo light', ARRAY['alto_proteina','portable'], ARRAY['perder_grasa','mantener'],
   2300, 'Mejor alternativa que jamonada para usuarios fitness.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-043', 'Ensalada de atún con huevo y papas', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   420, 560, 42, 45, 21, 6, 880,
   'atún, huevo, papa, verduras', ARRAY['alto_proteina','liviano'], ARRAY['perder_grasa','mantener'],
   2100, 'Buena comida de verano; ajustar papa según calorías.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-044', 'Sopaipillas al horno con pebre', 'Normal', 'Casero / Normal', ARRAY['colacion','once'],
   180, 390, 8, 58, 13, 4, 720,
   'zapallo, harina, pebre, poco aceite', ARRAY['chileno','antojo'], ARRAY['mantenimiento'],
   1100, 'Antojo chileno menos pesado si va al horno; no ideal para proteína.', 'https://fdc.nal.usda.gov/', 'estimado'),
  ('CL-045', 'Bowl vegetariano de quinoa, huevo y legumbres', 'Gourmet', 'Normal / Gourmet', ARRAY['almuerzo','cena'],
   420, 650, 32, 82, 22, 17, 620,
   'quinoa, huevo, garbanzos/lentejas, verduras, palta', ARRAY['vegetariano','alto_fibra'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   3300, 'Buena opción vegetariana completa; costo medio/alto por quinoa.', 'https://fdc.nal.usda.gov/', 'estimado')
on conflict (external_id) do nothing;
