-- Expands country-aware meal templates for LatAm, Spain and global staples.
-- pais_origen drives personalization by user country_code; GLOBAL is safe for
-- every user and is fetched together with the user's local country.

insert into public.ai_meal_templates
  (external_id, nombre, categoria_dificultad, modo_dieta, momento_dia,
   porcion_g, kcal, proteina_g, carbohidratos_g, grasas_g, fibra_g, sodio_mg,
   ingredientes_base, tags, objetivo_recomendado,
   costo_estimado_clp, nota_para_ia, source_url, confiabilidad, pais_origen)
values
  ('GLOBAL-001', 'Arroz con pollo basico', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   400, 610, 43, 82, 12, 4, 620,
   'arroz cocido, pechuga de pollo, aceite, verduras opcionales', ARRAY['global','alto_proteina'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   2200, 'Plato comun y adaptable; ajustar arroz segun objetivo.', 'https://fdc.nal.usda.gov/', 'estimado', 'GLOBAL'),
  ('GLOBAL-002', 'Arroz con carne magra', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   390, 680, 38, 78, 22, 4, 650,
   'arroz cocido, carne magra molida o picada, sofrito simple', ARRAY['global','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   2600, 'Opcion global alta en proteina; usar carne magra si el objetivo es perder grasa.', 'https://fdc.nal.usda.gov/', 'estimado', 'GLOBAL'),
  ('GLOBAL-003', 'Arroz con atun y tomate', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   350, 520, 34, 78, 9, 4, 720,
   'arroz cocido, atun al agua, tomate, cebolla opcional', ARRAY['global','rapido','alto_proteina'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1700, 'Muy rapido y comun; cuidar sodio del atun en lata.', 'https://fdc.nal.usda.gov/', 'estimado', 'GLOBAL'),
  ('GLOBAL-004', 'Pasta con pollo y salsa de tomate', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   420, 650, 42, 88, 14, 6, 680,
   'pasta, pechuga de pollo, salsa de tomate, aceite oliva', ARRAY['global','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   2400, 'Base mundial facil de adaptar; controlar porcion de pasta en deficit.', 'https://fdc.nal.usda.gov/', 'estimado', 'GLOBAL'),
  ('GLOBAL-005', 'Ensalada de huevo, papa y atun', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   420, 560, 42, 45, 21, 6, 700,
   'atun, huevo, papa cocida, lechuga, tomate', ARRAY['global','alto_proteina'], ARRAY['perder_grasa','mantener'],
   1900, 'Fresca y saciante; buena para dias calurosos o baja cocina.', 'https://fdc.nal.usda.gov/', 'estimado', 'GLOBAL'),

  ('AR-001', 'Milanesa de pollo al horno con pure', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   430, 690, 46, 62, 27, 5, 760,
   'pollo apanado al horno, pure de papas, ensalada', ARRAY['argentina','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   2600, 'Version al horno para bajar grasa frente a fritura tradicional.', 'https://fdc.nal.usda.gov/', 'estimado', 'AR'),
  ('AR-002', 'Bife magro con papas y ensalada', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   450, 720, 52, 48, 34, 5, 620,
   'bife magro, papas, lechuga, tomate, aceite oliva', ARRAY['argentina','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   3600, 'Plato argentino clasico; elegir corte magro para mejor perfil.', 'https://fdc.nal.usda.gov/', 'estimado', 'AR'),
  ('AR-003', 'Tarta de acelga y huevo', 'Normal', 'Vegetariano', ARRAY['almuerzo','cena'],
   320, 480, 22, 42, 24, 7, 640,
   'masa de tarta, acelga, huevo, queso', ARRAY['argentina','vegetariano'], ARRAY['perder_grasa','mantener'],
   1800, 'Opcion casera vegetariana; acompanar con ensalada para mas volumen.', 'https://fdc.nal.usda.gov/', 'estimado', 'AR'),
  ('AR-004', 'Locro liviano con carne magra', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   500, 650, 36, 82, 18, 12, 820,
   'maiz blanco, zapallo, porotos, carne magra, verduras', ARRAY['argentina','legumbres'], ARRAY['mantener','ganar_musculo'],
   2200, 'Plato tradicional denso; moderar embutidos para version fitness.', 'https://fdc.nal.usda.gov/', 'estimado', 'AR'),
  ('AR-005', 'Empanadas argentinas al horno con ensalada', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   360, 620, 30, 68, 24, 5, 780,
   'empanadas de carne al horno, lechuga, tomate', ARRAY['argentina'], ARRAY['mantener'],
   2300, 'Usar horno y sumar ensalada mejora saciedad sin subir tanto calorias.', 'https://fdc.nal.usda.gov/', 'estimado', 'AR'),

  ('CO-001', 'Bandeja paisa ligera', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   520, 760, 46, 86, 24, 14, 860,
   'frijoles, arroz, carne magra, huevo, platano, aguacate', ARRAY['colombia','alto_proteina','legumbres'], ARRAY['mantener','ganar_musculo'],
   3000, 'Version controlada en grasas; reducir chicharron o usar carne magra.', 'https://fdc.nal.usda.gov/', 'estimado', 'CO'),
  ('CO-002', 'Ajiaco de pollo', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   550, 580, 42, 68, 14, 7, 780,
   'pollo, papa, mazorca, guascas, crema opcional', ARRAY['colombia','alto_proteina'], ARRAY['perder_grasa','mantener'],
   2400, 'Sopa completa; controlar crema para mantener calorias moderadas.', 'https://fdc.nal.usda.gov/', 'estimado', 'CO'),
  ('CO-003', 'Arepa con pollo y aguacate', 'Muy fácil', 'Casero / Normal', ARRAY['desayuno','almuerzo','cena'],
   300, 520, 34, 52, 20, 6, 620,
   'arepa, pollo desmechado, aguacate, tomate', ARRAY['colombia','alto_proteina'], ARRAY['perder_grasa','mantener'],
   1900, 'Comun y portable; aumentar pollo para usuarios altos en proteina.', 'https://fdc.nal.usda.gov/', 'estimado', 'CO'),
  ('CO-004', 'Sancocho de pollo con arroz', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   600, 690, 43, 88, 16, 8, 820,
   'pollo, yuca, papa, platano, arroz, verduras', ARRAY['colombia'], ARRAY['mantener','ganar_musculo'],
   2500, 'Plato abundante; ajustar arroz si ya trae yuca y platano.', 'https://fdc.nal.usda.gov/', 'estimado', 'CO'),
  ('CO-005', 'Lentejas colombianas con arroz', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   450, 590, 26, 92, 12, 16, 690,
   'lentejas, arroz, zanahoria, papa, carne magra opcional', ARRAY['colombia','legumbres'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1500, 'Economica y saciante; buena base para planes de deficit o volumen.', 'https://fdc.nal.usda.gov/', 'estimado', 'CO'),

  ('PE-001', 'Lomo saltado con arroz controlado', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   430, 690, 42, 78, 22, 5, 820,
   'carne magra, arroz, papa, tomate, cebolla, salsa de soya', ARRAY['peru','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   3200, 'Reducir papa o arroz si el objetivo es deficit; cuidar sodio.', 'https://fdc.nal.usda.gov/', 'estimado', 'PE'),
  ('PE-002', 'Aji de gallina ligero con arroz', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   420, 660, 38, 70, 24, 4, 780,
   'pollo deshilachado, arroz, aji amarillo, pan o avena, leche', ARRAY['peru','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   2800, 'Version ligera usando menos crema y mas pollo.', 'https://fdc.nal.usda.gov/', 'estimado', 'PE'),
  ('PE-003', 'Ceviche con camote y choclo', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   380, 430, 38, 50, 7, 5, 720,
   'pescado blanco, limon, cebolla, camote, choclo', ARRAY['peru','alto_proteina','liviano'], ARRAY['perder_grasa','mantener'],
   3000, 'Alto en proteina y bajo en grasa; ideal para dias livianos.', 'https://fdc.nal.usda.gov/', 'estimado', 'PE'),
  ('PE-004', 'Arroz chaufa de pollo', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   420, 680, 40, 82, 20, 4, 860,
   'arroz, pollo, huevo, cebollin, salsa de soya', ARRAY['peru','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   2300, 'Usar poco aceite y soya baja en sodio mejora el perfil.', 'https://fdc.nal.usda.gov/', 'estimado', 'PE'),
  ('PE-005', 'Causa de pollo con palta', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   380, 610, 32, 62, 26, 6, 650,
   'papa amarilla, pollo, palta, limon, aji amarillo', ARRAY['peru'], ARRAY['mantener'],
   2600, 'Densa y saciante; ajustar palta/mayonesa segun calorias.', 'https://fdc.nal.usda.gov/', 'estimado', 'PE'),

  ('VE-001', 'Arepa reina pepiada ligera', 'Normal', 'Casero / Normal', ARRAY['desayuno','almuerzo','cena'],
   330, 590, 36, 52, 26, 7, 680,
   'arepa, pollo desmechado, aguacate, yogur o poca mayonesa', ARRAY['venezuela','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   2300, 'Usar yogur en vez de mayonesa reduce grasas sin perder textura.', 'https://fdc.nal.usda.gov/', 'estimado', 'VE'),
  ('VE-002', 'Pabellon criollo controlado', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   520, 760, 44, 96, 20, 15, 820,
   'carne mechada, arroz, caraotas negras, platano, queso opcional', ARRAY['venezuela','legumbres','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   3000, 'Plato completo; moderar platano frito o hacerlo al horno.', 'https://fdc.nal.usda.gov/', 'estimado', 'VE'),
  ('VE-003', 'Cachapa con queso y pollo', 'Normal', 'Casero / Normal', ARRAY['desayuno','almuerzo','cena'],
   380, 650, 35, 72, 24, 6, 720,
   'cachapa de maiz, queso fresco, pollo desmechado', ARRAY['venezuela','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   2600, 'Agregar pollo mejora proteina; controlar queso si se busca deficit.', 'https://fdc.nal.usda.gov/', 'estimado', 'VE'),
  ('VE-004', 'Asado negro con arroz y ensalada', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   430, 690, 44, 72, 22, 5, 760,
   'carne magra guisada, arroz, ensalada, salsa reducida', ARRAY['venezuela','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   3200, 'Preferir corte magro y porcion moderada de salsa dulce.', 'https://fdc.nal.usda.gov/', 'estimado', 'VE'),
  ('VE-005', 'Caraotas negras con arroz y huevo', 'Muy fácil', 'Vegetariano', ARRAY['almuerzo','cena'],
   430, 600, 27, 88, 16, 15, 690,
   'caraotas negras, arroz, huevo, sofrito', ARRAY['venezuela','vegetariano','legumbres'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1500, 'Economico y saciante; legumbre+cereal con huevo suma proteina.', 'https://fdc.nal.usda.gov/', 'estimado', 'VE'),

  ('ES-001', 'Tortilla espanola con ensalada', 'Normal', 'Vegetariano', ARRAY['almuerzo','cena'],
   360, 560, 24, 46, 30, 5, 620,
   'huevo, papa, cebolla, aceite oliva, ensalada', ARRAY['espana','vegetariano'], ARRAY['mantener'],
   2200, 'Controlar aceite para hacerla mas ligera.', 'https://fdc.nal.usda.gov/', 'estimado', 'ES'),
  ('ES-002', 'Paella de pollo y mariscos', 'Normal', 'Casero / Normal', ARRAY['almuerzo'],
   430, 650, 42, 82, 16, 5, 820,
   'arroz, pollo, mariscos, verduras, azafran', ARRAY['espana','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   3600, 'Completa y proteica; ajustar aceite y arroz segun objetivo.', 'https://fdc.nal.usda.gov/', 'estimado', 'ES'),
  ('ES-003', 'Gazpacho con atun y pan integral', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   420, 430, 30, 48, 13, 8, 650,
   'gazpacho, atun, pan integral, aceite oliva', ARRAY['espana','liviano','alto_proteina'], ARRAY['perder_grasa','mantener'],
   2100, 'Fresco y ligero; sumar atun lo vuelve mas completo.', 'https://fdc.nal.usda.gov/', 'estimado', 'ES'),
  ('ES-004', 'Lentejas estofadas con verduras', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   450, 580, 27, 82, 15, 17, 740,
   'lentejas, verduras, papa, chorizo opcional', ARRAY['espana','legumbres'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   1600, 'Evitar o reducir chorizo si el objetivo es perder grasa.', 'https://fdc.nal.usda.gov/', 'estimado', 'ES'),
  ('ES-005', 'Pollo al ajillo con patata cocida', 'Normal', 'Casero / Normal', ARRAY['almuerzo','cena'],
   420, 620, 48, 50, 24, 5, 700,
   'pollo, ajo, patata cocida, ensalada, aceite oliva', ARRAY['espana','alto_proteina'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   2600, 'Alta proteina; controlar aceite de coccion.', 'https://fdc.nal.usda.gov/', 'estimado', 'ES'),

  ('MX-001', 'Tacos de pollo con frijoles', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   360, 610, 42, 68, 18, 12, 760,
   'tortillas de maiz, pollo, frijoles, pico de gallo, aguacate', ARRAY['mexico','alto_proteina'], ARRAY['perder_grasa','mantener','ganar_musculo'],
   2300, 'Usar tortillas de maiz y pollo magro mantiene buen perfil.', 'https://fdc.nal.usda.gov/', 'estimado', 'MX'),
  ('MX-002', 'Bowl de frijoles, arroz y carne asada', 'Muy fácil', 'Casero / Normal', ARRAY['almuerzo','cena'],
   450, 720, 46, 88, 20, 14, 780,
   'frijoles, arroz, carne asada magra, pico de gallo', ARRAY['mexico','legumbres','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   2800, 'Muy completo para volumen; reducir arroz para deficit.', 'https://fdc.nal.usda.gov/', 'estimado', 'MX'),
  ('MX-003', 'Chilaquiles verdes con pollo', 'Normal', 'Casero / Normal', ARRAY['desayuno','almuerzo'],
   380, 620, 36, 62, 26, 8, 820,
   'totopos horneados, salsa verde, pollo, queso fresco, crema opcional', ARRAY['mexico','alto_proteina'], ARRAY['mantener','ganar_musculo'],
   2500, 'Hornear totopos y moderar crema mejora calorias.', 'https://fdc.nal.usda.gov/', 'estimado', 'MX')
on conflict (external_id) do nothing;
